version: '3'

services:
  pfe-ree-node:
    image: registry.plt.et.tu-dresden.de/pfe-ree-node:latest
    ports:
      - "3000:3000"
    command: "--fixReactor"
  pfe-ree-viz:
    image: registry.plt.et.tu-dresden.de/pfe-ree-viz:latest
    ports:
      - "80:80"
    depends_on:
      - pfe-ree-node
  mtp-converter:
    image: registry.plt.et.tu-dresden.de/mtp-converter:latest
    ports:
      - "3031:3031"
    depends_on:
      - pfe-ree-node
  pfe-dashboard:
    image: registry.plt.et.tu-dresden.de/pfe-dashboard:latest
    ports:
      - "8081:80"
    depends_on:
      - opcua-rest-api
  pfe-angularjs-dashboard:
    image: registry.plt.et.tu-dresden.de/pfe-angularjs-dashboard:latest
    ports:
      - "8079:80"
    depends_on:
      - opcua-rest-api
  opcua-rest-api:    
    image: registry.plt.et.tu-dresden.de/opcua-rest-api:latest
    environment:
      # localhost is not supported. please use host ip if necessary
      - OPCUA_URL=opc.tcp://10.0.54.56:48010
    ports:
      # change first port according to topology
      - "1204:1200"
  opcua-rest-api-dose:    
    image: registry.plt.et.tu-dresden.de/opcua-rest-api:latest
    environment:
      # localhost is not supported. please use host ip if necessary
      - OPCUA_URL=opc.tcp://10.6.51.21:4840
    restart: on-failure:5 
    ports:
      # change first port according to topology
      - "1200:1200"
  opcua-rest-api-react:    
    image: registry.plt.et.tu-dresden.de/opcua-rest-api:latest
    environment:
      # localhost is not supported. please use host ip if necessary
      - OPCUA_URL=opc.tcp://10.6.51.22:4840
    restart: on-failure:5 
    ports:
      # change first port according to topology
      - "1201:1200"
  opcua-rest-api-temper:    
    image: registry.plt.et.tu-dresden.de/opcua-rest-api:latest
    environment:
      # localhost is not supported. please use host ip if necessary
      - OPCUA_URL=opc.tcp://10.6.51.24:4840
    restart: on-failure:5 
    ports:
      # change first port according to topology
      - "1202:1200"
  
